[colors.bright]
black = "#404040"
blue = "#4e9fb1"
cyan = "#42717b"
green = "#a0cf5d"
magenta = "#8542ff"
red = "#d23d3d"
white = "#000000"
yellow = "#f39d21"

[colors.cursor]
cursor = "#f39d21"
text = "#000000"

[colors.normal]
black = "#000000"
blue = "#7dc1cf"
cyan = "#6d878d"
green = "#b8d68c"
magenta = "#9b64fb"
red = "#e84f4f"
white = "#dddddd"
yellow = "#e1aa5d"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.vi_mode_cursor]
cursor = "#f39d21"
text = "#000000"

[font]
size = 8

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 2
y = 1

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[window.padding]
x = 2
